spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true # 确保 Flyway 启用
    baseline-on-migrate: true
    locations: classpath:db/migration # Flyway 脚本路径，默认是这个路径
